service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  testing:
    handler: src/index.handler
    timeout: 60 # seconds
    memorySize: 128 # mb
