name: 'Build and upload to S3 Bucket'

on: 
  push:
    branches: 
      - main

jobs:
  Build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Building and testing on development server on branch $GITHUB_REF"
      - name: AWS Test Configuration
        if: ${{ success() }}
        id: check2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Copy Build to S3
        if: ${{ success() }}
        run: |
          npm install
          npm run build:ci
          aws s3 cp build s3://regov-artifacts-dev/artifacts/build --recursive
        # ${{ secrets.AWS_S3_Artifacts }}

      - name: Publish Artifacts
        if: ${{ success() }}
        id: check3
        uses: actions/upload-artifact@v2
        with:
          name: latest-build
          path: build
          #path: ${{ secrets.AWS_S3_Artifacts }}
          
          
